import type { Product } from "@/lib/configurator/types";

// ⚠️ PRODUITS FICTIFS — usage exclusivement interne au moteur pour la
// validation des cas de test (voir KRISALYS-Phase3-Configurateur-Audit.md,
// cas A à L). Ne JAMAIS importer ce fichier depuis un composant React ou
// une page de production. Volontairement placé sous lib/configurator/ et
// non sous data/, pour ne jamais être confondu avec le catalogue réel
// (data/products.ts).
export const testProducts: Product[] = [
  {
    supplier: "TEST",
    manufacturer: "TEST",
    technology: "film-led-transparent",
    model: "TEST-FILM-A",
    sku: null,
    pitch: 6.25,
    pricePerM2: null,
    priceStatus: "placeholder",
    transparency: null,
    brightness: null,
    brightnessMax: null,
    viewingAngle: null,
    pixelDensity: 25600,
    powerPeak: null,
    powerAverage: null,
    weight: null,
    thickness: null,
    refreshRate: null,
    operatingTemperature: null,
    humidity: null,
    moduleWidth: null,
    moduleHeight: null,
    source: "Produit fictif de test — jamais affiché en production",
    validationStatus: "unverified",
    active: true,
  },
  {
    supplier: "TEST",
    manufacturer: "TEST",
    technology: "film-led-transparent",
    model: "TEST-FILM-B",
    sku: null,
    pitch: 10,
    pricePerM2: null,
    priceStatus: "placeholder",
    transparency: null,
    brightness: null,
    brightnessMax: null,
    viewingAngle: null,
    pixelDensity: 10000,
    powerPeak: null,
    powerAverage: null,
    weight: null,
    thickness: null,
    refreshRate: null,
    operatingTemperature: null,
    humidity: null,
    moduleWidth: null,
    moduleHeight: null,
    source: "Produit fictif de test — jamais affiché en production",
    validationStatus: "unverified",
    active: true,
  },
  {
    supplier: "TEST",
    manufacturer: "TEST",
    technology: "ecran-led-transparent",
    model: "TEST-ECRAN-A",
    sku: null,
    pitch: 8,
    pricePerM2: null,
    priceStatus: "placeholder",
    transparency: null,
    brightness: null,
    brightnessMax: null,
    viewingAngle: null,
    pixelDensity: 15625,
    powerPeak: null,
    powerAverage: null,
    weight: null,
    thickness: null,
    refreshRate: null,
    operatingTemperature: null,
    humidity: null,
    moduleWidth: null,
    moduleHeight: null,
    source: "Produit fictif de test — jamais affiché en production",
    validationStatus: "unverified",
    active: true,
  },
  {
    supplier: "TEST",
    manufacturer: "TEST",
    technology: "ecran-led-transparent",
    model: "TEST-ECRAN-NULL",
    sku: null,
    pitch: 10,
    pricePerM2: null,
    priceStatus: "placeholder",
    transparency: null,
    brightness: null,
    brightnessMax: null,
    viewingAngle: null,
    pixelDensity: null,
    powerPeak: null,
    powerAverage: null,
    weight: null,
    thickness: null,
    refreshRate: null,
    operatingTemperature: null,
    humidity: null,
    moduleWidth: null,
    moduleHeight: null,
    source: "Produit fictif de test — jamais affiché en production",
    validationStatus: "unverified",
    active: true,
  },
];
